CREATE DATABASE BTVN2_QLGIAOVU
GO

USE BTVN2_QLGIAOVU
GO
 
 DROP TABLE MONHOC
--CREATE TABLE MONHOC
CREATE TABLE MONHOC
(
	MAMH VARCHAR(10) PRIMARY KEY NOT NULL,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
)

DROP TABLE LOP
--CREATE TABLE LOP
CREATE TABLE LOP
(
	MALOP VARCHAR(3) PRIMARY KEY NOT NULL,
	TENLOP VARCHAR(40),
	TRGLOP VARCHAR(5),
	SISO TINYINT, 
	MAGVCN VARCHAR(4)
)
drop table Khoa
--CREATE TABLE KHOA
CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4) PRIMARY KEY NOT NULL,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA VARCHAR(4)
)

DROP TABLE HOCVIEN
--CREATE TABLE HOCVIEN
CREATE TABLE HOCVIEN
(
	MAHV VARCHAR(5) PRIMARY KEY NOT NULL,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3) CHECK(GIOITINH IN ('Nam','Nu')),
	NOISINH VARCHAR(40),
	MALOP VARCHAR(3)
)
DROP TABLE DIEUKIEN
--CREATE TABLE DIEUKIEN
CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10) NOT NULL,
	MAMH_TRUOC VARCHAR(10) NOT NULL,
	PRIMARY KEY(MAMH, MAMH_TRUOC)
)

DROP TABLE GIAOVIEN
--CREATE TABLE GIAOVIEN
CREATE TABLE GIAOVIEN
(
	MAGV VARCHAR(4) NOT NULL PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3) CHECK (GIOITINH IN ('Nam','Nu')),
	NGSINH SMALLDATETIME, 
	NGLV SMALLDATETIME,
	HESO NUMERIC(4,2),
	MLUONG MONEY,
	MAKHOA VARCHAR(4)
)

DROP TABLE GIANGDAY
--CREATE TABLE GIANGDAY
CREATE TABLE GIANGDAY
(
	MALOP VARCHAR(3) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	MAGV VARCHAR(4), 
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY (MALOP, MAMH)
)

drop table KETQUATHI
--CREATE TABLE KETQUATHI
CREATE TABLE KETQUATHI
(
	MAHV VARCHAR(5) NOT NULL,
	MAMH VARCHAR(10) NOT NULL,
	LT TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KETQUA VARCHAR(10) CHECK (KETQUA IN ('Dat', 'Khong Dat')),
	PRIMARY KEY (MAHV, MAMH,LT)
)
