CREATE DATABASE BTVN2_QLGIAOVU
GO

USE BTVN2_QLGIAOVU
GO
 
 --CREATE TABLE KHOA
CREATE TABLE KHOA
(
	MAKHOA VARCHAR(4) PRIMARY KEY,
	TENKHOA VARCHAR(40),
	NGTLAP SMALLDATETIME,
	TRGKHOA CHAR(4)
)
GO

--CREATE TABLE MONHOC
CREATE TABLE MONHOC
(
	MAMH VARCHAR(10) PRIMARY KEY,
	TENMH VARCHAR(40),
	TCLT TINYINT,
	TCTH TINYINT,
	MAKHOA VARCHAR(4)
)
GO

--CREATE TABLE DIEUKIEN
CREATE TABLE DIEUKIEN
(
	MAMH VARCHAR(10),
	MAMH_TRUOC VARCHAR(10),
	PRIMARY KEY(MAMH, MAMH_TRUOC)
)
GO

--CREATE TABLE GIAOVIEN
CREATE TABLE GIAOVIEN
(
	MAGV CHAR(4) PRIMARY KEY,
	HOTEN VARCHAR(40),
	HOCVI VARCHAR(10),
	HOCHAM VARCHAR(10),
	GIOITINH VARCHAR(3) CHECK (GIOITINH IN ('Nam','Nu')),
	NGSINH SMALLDATETIME, 
	NGLV SMALLDATETIME,
	HESO NUMERIC(4,2),
	MLUONG MONEY,
	MAKHOA VARCHAR(4)
)
GO

--CREATE TABLE LOP
CREATE TABLE LOP
(
	MALOP CHAR(3) PRIMARY KEY,
	TENLOP VARCHAR(40),
	TRGLOP CHAR(5),
	SISO TINYINT, 
	MAGVCN CHAR(4)
)
GO



--CREATE TABLE HOCVIEN
CREATE TABLE HOCVIEN
(
	MAHV CHAR(5) PRIMARY KEY ,
	HO VARCHAR(40),
	TEN VARCHAR(10),
	NGSINH SMALLDATETIME,
	GIOITINH VARCHAR(3) CHECK(GIOITINH IN ('Nam','Nu')),
	NOISINH VARCHAR(40),
	MALOP CHAR(3)
)
GO

--CREATE TABLE GIANGDAY
CREATE TABLE GIANGDAY
(
	MALOP CHAR(3) ,
	MAMH VARCHAR(10),
	MAGV CHAR(4), 
	HOCKY TINYINT,
	NAM SMALLINT,
	TUNGAY SMALLDATETIME,
	DENNGAY SMALLDATETIME,
	PRIMARY KEY (MALOP, MAMH)
)
GO

--CREATE TABLE KETQUATHI
CREATE TABLE KETQUATHI
(
	MAHV CHAR(5),
	MAMH VARCHAR(10),
	LT TINYINT,
	NGTHI SMALLDATETIME,
	DIEM NUMERIC(4,2),
	KETQUA VARCHAR(10) CHECK (KETQUA IN ('Dat', 'Khong Dat')),
	PRIMARY KEY (MAHV, MAMH,LT)
)
GO