USE BTVN2_QLGIAOVU

--CREATE FK OF HOCVIEN
ALTER TABLE HOCVIEN
ADD CONSTRAINT FK_HOCVIEN_LOP
FOREIGN KEY (MALOP)
REFERENCES LOP(MALOP)

--CREATE FK OF LOP
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_HOCVIEN
FOREIGN KEY (TRGLOP)
REFERENCES HOCVIEN(MAHV)

--CREATE FK OF LOP
ALTER TABLE LOP
ADD CONSTRAINT FK_LOP_GIAOVIEN
FOREIGN KEY (MAGVCN)
REFERENCES GIAOVIEN(MAGV)

--CREATE FK OF KHOA
ALTER TABLE KHOA
ADD CONSTRAINT FK_KHOA_GIAOVIEN
FOREIGN KEY (TRGKHOA)
REFERENCES GIAOVIEN(MAGV)

--CREATE FK OF MONHOC
ALTER TABLE MONHOC
ADD CONSTRAINT FK_MONHOC_KHOA
FOREIGN KEY (MAKHOA)
REFERENCES KHOA(MAKHOA)

--CREATE FK OF DIEUKIEN
ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOC
FOREIGN KEY (MAMH)
REFERENCES MONHOC(MAMH)

ALTER TABLE DIEUKIEN
ADD CONSTRAINT FK_DIEUKIEN_MONHOCTRUOC
FOREIGN KEY (MAMH_TRUOC)
REFERENCES MONHOC(MAMH)

--CREATE FK OF GIAOVIEN
ALTER TABLE GIAOVIEN
ADD CONSTRAINT FK_GIAOVIEN_KHOA
FOREIGN KEY (MAKHOA)
REFERENCES KHOA(MAKHOA)

--CREATE FK OF GIANGDAY
ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_LOP
FOREIGN KEY (MALOP)
REFERENCES LOP(MALOP)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_MONHOC
FOREIGN KEY (MAMH)
REFERENCES MONHOC(MAMH)

ALTER TABLE GIANGDAY
ADD CONSTRAINT FK_GIANGDAY_GIAOVIEN
FOREIGN KEY (MAGV)
REFERENCES GIAOVIEN(MAGV)

--CREATE FK OF KETQUATHI
ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_HOCVIEN
FOREIGN KEY (MAHV)
REFERENCES HOCVIEN(MAHV)

ALTER TABLE KETQUATHI
ADD CONSTRAINT FK_KETQUATHI_MONHOC
FOREIGN KEY (MAMH)
REFERENCES MONHOC(MAMH)

